package com.lich.lvn;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.lich.lvn.model.DanhNgon;

public class DanNgonUnit {
	public static List<DanhNgon> danhNgonList = null;
	static {
		danhNgonList = new ArrayList<>();
		DanhNgon dn = new DanhNgon("Biết cười và biết chọc cười là hai thuộc tính của con người","H.Bergson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tiếng cười ồn ào biểu hiện sự trống rỗng của tâm trí","Olivier Goldsmith");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kẻ cười đầu tiên là kẻ cười sau cùng","Bennekin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy mỉm cười với mọi người và đặt chân tình trong mỗi cái bắt tay","Tục ngữ Pháp");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thấy miệng cười mà mắt không cười thì chớ có tin","A. D. Houdetot");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trong tất cả loại giả vờ, giả vờ cười là khó nhất","N. Bơrixôva");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không có điều gì trên đời khiến chúng ta phải sợ. Chỉ có những điều chúng ta cần phải hiểu","Marie Curie");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giáo dục một người là đào luyện họ có thể đối đầu với mọi hoàn cảnh","Ch. Rivet");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không có người bạn nào tốt hơn khoa học, không có người bạn nào xấu hơn bệnh tật","Ngạn ngữ Ấn Độ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giáo dục là vũ khí mạnh nhất mà người ta có thể sử dụng để thay đổi cả thế giới","Nelson Mandela");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không phải sức mạnh cơ bắp làm bá chủ, mà sự thông minh làm bá chủ ở khắp nơi","Sophocles");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khiến thiên hạ thái bình là nhờ tới nhân tài, khiến nhân tài đạt tới thành công là nhờ giáo hóa","Hồ Viên");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con người nhờ sự học mà thành cao quý nhiều hơn bản chất","Cicero");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi luôn cảm thấy mình trẻ trung vui vẻ vì tôi không ngừng học tập, không ngừng làm việc","Maxime Gorki");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tiêu chuẩn đánh giá con người là khát vọng vươn tới sự hoàn chỉnh","Johann Wolfgang von Goethe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỗ toàn mỹ của con người không phải ở nơi quyền lực mà là nơi sự hoàn thiện của chính mình","Tagore");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để cưới được một vị học giả cho con gái, cho dù phải bán hết tài sản cũng đáng. Để lấy được con gái một vị học giả, cho dù là phải bỏ ra toàn bộ tài sản cũng không tiếc","Ngạn ngữ Do Thái");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy dạy đạo đức cho con cái bạn, chỉ có đạo đức chứ không phải vàng bạc mới làm chúng sung sướng","Beethoven");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi con trai bạn còn nhỏ, bạn hãy làm ông chủ của nó. Nhưng khi nó lớn lên rồi, bạn hãy làm người anh của nó","Ngạn ngữ Arập");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng xấu hổ khi không biết, chỉ xấu hổ khi không học","Ngạn ngữ Nga");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hỏi một câu, chỉ dốt nát trong chốc lát. Không dám hỏi sẽ dốt nát suốt đời","Danh ngôn phương Tây");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cách hữu hiệu nhất để làm tăng thêm trí thông minh của các nhà thông thái, là làm giảm bớt con số của họ đi","Alexis Carrel");
		danhNgonList.add(dn);
		dn = new DanhNgon("Muốn uốn cây cong cho thẳng lại, ta uốn cong nó theo chiều ngược lại","Michel de Montaigne");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự học, trước hết phải biết phân biệt việc nghĩa với việc hại","Trương Thức");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đàm luận làm giàu kiến thức, nhưng sự đơn độc lại là trường học của tài năng","Cibbone");
		danhNgonList.add(dn);
		dn = new DanhNgon("Biết bao kẻ đọc sách và học hỏi, không phải để tìm ra chân lý mà là để gia tăng những gì mình đã biết","Julien Green");
		danhNgonList.add(dn);
		dn = new DanhNgon("Các yếu tố của nghệ thuật học tập là ý chí, trật tự và thời gian","M. Prévost");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tất cả mọi người đều ao ước có được nhiều hiểu biết, điều kiện đầu tiên là phải biết nhìn đời với cặp mắt của đứa trẻ thơ, cái gì cũng mới lạ và làm cho ta ngạc nhiên cả","Aristotle");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đối với kẻ biết nghe, chỉ cần nói nửa lời","Plaute");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ta không bao giờ trở nên thông thái được nếu chỉ chịu đọc hay chịu học những gì mình thích mà thôi","Rubet");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gặp được một quyển sách hay, nên mua liền dù đọc được hay không đọc được, vì sớm muộn gì cũng cần đến nó","Winton Sir Churchill");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi nghi tất cả những gì tôi chưa rõ. Thà phải tìm hiểu sự thực suốt đêm còn hơn phải nghi ngờ nó suốt đời","F.Engels");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người đọc biết nhiều nhưng người quan sát còn biết nhiều hơn","Alexandre Dumas, fils");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học rộng điều gì không bằng hiểu rành điều ấy.  Hiểu rành điều ấy không gì bằng thực hành điều ấy","Châu Hy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học mà không suy nghĩ thì vô ích.  Suy nghĩ mà không học thì nguy hiểm","Khổng Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học là vấn đề không bao giờ cạn.  Còn sống ngày nào thì phải học thêm ngày ấy","Beaugrand");
		danhNgonList.add(dn);
		dn = new DanhNgon("Biết ôn lại những điều đã học để biết thêm điều mới, người ấy có thể làm thầy thiên hạ","Khổng Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những gì ta biết chỉ là một phần rất nhỏ.  Người biết đủ là người biết phương cách học hỏi","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cần phải học nhiều để nhận thức được mình biết ít","M. Môngten");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một người đều hấp thụ được hai thứ giáo dục: một thứ do người khác tặng cho mình, và thứ kia quan trọng hơn nhiều, do chính mình tự tặng cho bản thân","Edward Gibbon");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi chưa bao giờ gặp một người nào mà tôi không tìm thấy nơi họ một cái gì đáng cho tôi học hỏi","Afred de Vigny");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kẻ tự cho mình là giỏi thì tai không còn nghe được lời hay lẽ thiệt nữa","Gia ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sở dĩ người ta ít nhớ những điều đã đọc được chính là vì tại người ta tự suy nghĩ quá ít","G. Lin_then_béc");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đọc sách cần phải: một là, thấu hiểu và phê phán; hai là, cùng với bạn bè hoặc trong khung cảnh ra đình, ba là đọc đi đọc lại cái đã đọc, bốn là với cây bút trong tay","P. Pốt_te");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng đọc gì anh không muốn nhớ và đừng nhớ gì anh không định dùng","G.Blecki");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có ba thứ ngu dốt: Không biết những gì mình cần biết, không biết rõ những gì mình biết và biết những gì mình không cần biết","La Rochefoucauld");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ngu dốt không đáng thẹn bằng thiếu ý chí học hỏi","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hoàn toàn tin vào sách thà không có sách còn hơn","Mạnh Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Điều dở không cần phải học tập, nó phát sinh tự nhiên như những bụi gai mọc nơi hoang địa","La Cordaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trí thông minh của chúng ta bắt nguồn từ kinh nghiệm, còn kinh nghiệm - từ những sự ngu dốt của chúng ta","X. Gitri");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tất cả mọi sự hiểu biết đều ra hoài nghi mà thành","Anđrơ Giđơ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ba cái nền tảng của học vấn là: nhận xét nhiều, từng trải nhiều và học tập nhiều","Catherall");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trí tuệ là kẻ chinh phục số phận","Ngạn ngữ Anh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sách là con thuyền chở tri thức đến cho mọi người","E. Xuy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tri thức làm người ta khiêm tốn, ngu si làm người ta kiêu ngạo","Ngạn ngữ Anh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ích lợi lớn nhất của kiến thức là giúp ta hiểu rõ bản thân và dạy ta biết cách xử thế","S. Ambroise");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự hiểu biết là kho báu của cuộc sống. Nó mang đến cho con người niềm vui và hạnh phúc","C. G. Pautôpxki");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để cho con một rương vàng không bằng để cho con một cuốn sách","Cổ ngữ Trung Hoa");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự ngu dốt là một vết nhơ dễ trông thấy hơn hết","Paul Morand");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sức lực có thể bị cạn kiệt nhưng kiến thức thì không bao giờ","Ngạn ngữ Mông Cổ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những kẻ trí tuệ tầm thường hay lên án những gì vượt quá tầm hiểu biết của họ","La Rochefoucauld");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có học vấn mà không có đạo đức là người ác, có đạo đức mà không có học vấn là người hèn","La Tư Pháp");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bao giờ cũng nên có nhiều trí tuệ hơn lòng tự ái","Epiquya");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy hòa mình vào xã hội vì cái đầu anh quá nhỏ để xã hội có thể hội nhập vào đó","G. C. Lichtenberg");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người ta không thể sống cho tất cả mọi người nhất là cho những người mình ta không muốn sống cho họ","Johann Wolfgang von Goethe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Xã hội tồn tại vì lợi ích của con người, chứ không phải con người tồn tại vì lợi ích của xã hội","Herbert Spencer");
		danhNgonList.add(dn);
		dn = new DanhNgon("Xã hội là một quyển sách tốt, nó giúp rất ít cho những kẻ không biết đọc nó","Goldoni");
		danhNgonList.add(dn);
		dn = new DanhNgon("Xã hội như một con tàu mỗi người đều phải góp sức vào sự điều khiển lái","Henrik Ibsen");
		danhNgonList.add(dn);
		dn = new DanhNgon("Xã hội là một rạp hát trong đó những kẻ xấu chiếm giữ những chỗ tốt","Aristonvma");
		danhNgonList.add(dn);
		dn = new DanhNgon("Luật pháp là cái mạng nhện mà những con ruồi to thì chui lọt, còn những con nhỏ thì bị mắc lưới","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Pháp luật cũng như nhà cửa, cái này tựa vào cái kia","Edmund Burke");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nơi nào mà luật pháp chấm dứt là sự hung bạo bắt đầu","William Pitt");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những luật pháp quá mềm dịu thì không được tuân theo, những luật pháp quá cứng rắn thì không áp dụng được","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Pháp luật được những người già làm ra. Những người trẻ tuổi và đàn bà thích sự ngoại trừ, những người già muốn sự khuôn khổ","Johann Wolfgang von Goethe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Pháp luật được các nhà thông thái đặt ra, không phải để họ khỏi phạm phải sự bất công, mà để họ khỏi phải chịu sự bất công","Epicure");
		danhNgonList.add(dn);
		dn = new DanhNgon("Luật pháp luôn luôn có lợi cho kẻ có của và nguy hại cho kẻ không có gì cả","Jean Jacques Rousseau");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những phong tục xấu làm nảy sinh những luật pháp tốt","Macrobe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Càng có nhiều luật pháp, càng thêm nhiều kẻ trộm","Lão Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Phải soi sáng lịch sử bằng luật pháp và soi sáng luật pháp bằng lịch sử","Montesquieu");
		danhNgonList.add(dn);
		dn = new DanhNgon("Luật pháp là một quốc gia thay đổi theo thời gian","Eschyle");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những biện pháp phi pháp có thể trở thành chính thức khi cần thiết","Abraham Lincoln");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôn giáo không làm cho người ta tốt , nhưng nó có thể ngăn cản không cho người ta trở nên xấu","Louis De Bonald");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hay nóng giận nản lòng là triệu chứng của một tâm hồn yếu đuối","Denis Diderot");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người nghiêm túc không bao giờ lấy chiếc lá nhỏ để che đậy sự thật trần trụi","G. L. Boan");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lạc quan thật sự không phải tin rằng mọi việc sẽ tốt đẹp, mà tin rằng không phải mọi việc sẽ tồi tệ","Dutour");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người lạc quan ngắm bông hồng mà quên gai nhọn.  Kẻ bi quan chỉ thấy gai nhọn mà quên bông hồng","K. Cubran");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cần lạc quan khi khởi đầu công việc và đầy hoài nghi khi kết thúc công việc","Ghéc-xen");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bi quan là tâm trạng, lạc quan là ý chí","A. len");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người lạc quan có lẽ đã thấy một ánh sáng trong bóng tối. Nhưng tại sao người bi quan lại chạy đến thổi tắt nó đi","Michel De Pierre");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đầu hàng cám dỗ là hành động của thú tính, chiến thắng nó mới là con người","Waterstone");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giá trị đầu tiên của mỗi con người là biết tự chủ, biết điều khiển ý chí và hành động của mình theo lí trí và đức tin","P. Deravigran");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy là nguyên bản của chính mình, thay vì là bản sao của người khác","Judy Garland");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gặp gỡ chính con người thực của mình phải là ưu tiên hàng đầu của bạn","Tom Hopkins");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hoàn thành nghĩa vụ tinh thần trong cuộc sống hằng ngày là điều trọng yếu cho sự sống còn của chúng ta","Winton Sir Churchill");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một trong những bước ngoặt đánh dấu sự trưởng thành của chúng ta là khi chúng ta khám phá ra sức mạnh bên trong ta giúp ta vượt qua tất cả những gì gây xúc phạm đến tự ái của mình","Max Lerner");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự thật đắng cay nào cũng có những hương vị ngọt ngào riêng của nó. Thành thật không phải ở chỗ nói tất cả những gì mình nghĩ mà là nghĩ đến tất cả những gì mình nói","H. D. Livry");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bí quyết lớn nhất của thành công là thành thật. Không thành thật, không có phương pháp nào tác dụng với bạn hết","E. Wheeler");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi nào nghi ngờ bạn hãy chỉ nói sự thật","Mactoes");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự thật tự nó có thể chiến thắng, nhưng dối trá thì cần phải có người giúp đỡ","Epictec");
		danhNgonList.add(dn);
		dn = new DanhNgon("Càng ngày tôi càng tin tưởng vào tác dụng duy nhất của sự thật; nó giúp chúng ta hiểu rõ: dối trá quả là có lợi","P. Đragiep");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đối với tấm lòng đại lượng, món nợ nặng nhất là lòng biết ơn khi chúng ta không có khả năng đền đáp","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người độc ác là địa ngục của chính mình","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Can đảm không phải là không sợ hãi. Can đảm chỉ là hành động thay vì ngồi đó sợ hãi","Mark Twain");
		danhNgonList.add(dn);
		dn = new DanhNgon("Can đảm không phải là liều chết mà là biết chống chọi lúc tai nạn","Lucius Annaeus Seneca");
		danhNgonList.add(dn);
		dn = new DanhNgon("Can đảm có nghĩa là vững vàng và sáng suốt trong cơn nguy cấp","V. Cousin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Can đảm là đức hạnh số một của con người vì nó đảm bảo cho tất cả những hạnh phúc khác","Churchill");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn không thể nào trở nên can đảm nếu bạn chỉ gặp toàn những điều tuyệt vời","Mary Tyler Moore");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dũng cảm: Đó là trách nhiệm được ý thức đến cùng","Paplenko");
		danhNgonList.add(dn);
		dn = new DanhNgon("Can đảm gia tăng khi người ta dám liều và nỗi sợ sệt cũng gia tăng khi người ta do dự. Trong tình thế nguy cấp, sự liều lĩnh thay thế cho sự khôn ngoan","Publilius Syrus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sau sự can đảm, không gì đẹp bằng lời thú nhận sự nhút nhát của mình","Helvétius");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người hà tiện nói mình cần kiệm, anh nhát nói mình cẩn thận","Tây Phương");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai hỏi với sự rụt rè nhút nhát là bảo cách cho người ta từ chối","Lucius Annaeus Seneca");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự khiêm tốn là một đức tính, sự rụt rè nhút nhát là một thói xấu","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đường đi khó không phải vì ngăn sông cách núi. Mà khó vì lòng người ngại núi e sông","Nguyễn Bá Học");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không có nghèo gì bằng không có tài, không có gì hèn bằng không có chí","C. C. Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Điều không là ta đau đớn thì sẽ làm ta mạnh mẽ hơn","Wilhelm Friedrich Nietzche");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đòn bẩy mạnh nhất trong các đòn bẩy: đó là ý chí","Lemenais");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ý chí tiến tới đâu, khó khăn lùi đến đó","Phương ngôn Ba Lan");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ý chí là sức mạnh để bắt đầu công việc một cách đúng lúc","Ralph Waldo Emerson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nhắm mắt trước hiểm nguy là phó thác và khước từ ý chí tự do của chính mình","G.Meredith");
		danhNgonList.add(dn);
		dn = new DanhNgon("Muốn cầu tiến hơn người, ra đời phải biết ngước mặt nhìn lên. Vì nhìn xuống ta thấy hơn người, nhưng nhìn lên, ta chỉ là con số không vĩ đại","Francois Mauriac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tinh thần của con người còn mạnh mẽ hơn bất kỳ tai ương nào giáng xuống trên con người","C. C. Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi không sợ bão tố, vì tôi đang học cách lái con thuyền của tôi","Louisa May Alcott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự khôn ngoan chỉ tìm thấy ở trong sự thật thà mà thôi","Johann Wolfgang von Goethe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trong tình thế nguy cấp, sự liều lĩnh sẽ thay thế cho sự khôn ngoan","Publilius Syrus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nghĩ sâu, tính xa thì không cùng khốn","Tô Thư");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người khéo thường bận, người khôn hay lo","Trang Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự khôn ngoan của cuộc sống luôn sâu xa, rộng lớn hơn sự khôn ngoan của con người","Maxime Gorki");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không có trí thông minh thì sự ngu đần cũng thành vô nghĩa","Papiriné");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có những người quá thông minh khiến cho người ta phải tự hỏi có còn cái gì làm cho họ chú ý đến nữa không?","Martin Du Gard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cha tôi thường nói với tôi: Đừng bao giờ làm mất sự dốt nát của con; con không thể nào thay thế được nó","Erich M. Remarque");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không biết về sự dốt nát của mình, đó là cái bệnh của kẻ dốt nát","Amos Bronson Alcott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mức ngu xuẩn thứ nhất là tự nhận mình thông minh, thứ hai là phô bày điều đó và thứ ba là xem thường lời khuyên, góp ý","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỉ có những thằng ngốc và người chết là chẳng bao giờ thay đổi ý kiến","S. Saplin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỉ có tên ngốc mới tin rằng kẻ tự phụ là người có tài năng","Jean De La Bruyère");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lòng hối hận là nguồn lợi cuối cùng mà người ta lấy ra từ trong lỗi lầm","Alexandre Dumas");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hối hận là một sự phán xét mà người ta dùng để chống lại chính mình","Menander");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bắt đầu biết hối hận là bắt đầu một cuộc sống mới","George Eliot");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự hối hận mở đầu cho đức hạnh như bình minh mở đầu cho ngày","Lacordaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự hối hận đến quá trễ khi nó không thể hàn gắn tội lỗi","F. J. Desbillous");
		danhNgonList.add(dn);
		dn = new DanhNgon("Họ giải quyết vấn đề này thật đơn giản: công nhận nó là vấn đề không thể giải quyết nổi","V. Batôsêvich");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ngôn từ mộc mạc mà hàm ý sâu xa là cách nói năng rất giỏi. Việc làm đơn giản mà hiệu quả thật lớn là cách làm rất hay","Mạnh Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai ghét sự bất nhân, sợ nó lây đến mình thì đã là người biết làm điều nhân","Khổng Tử");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai cũng có lúc sai lầm, càng trẻ lại càng bỡ ngỡ. Nếu ta quá sốt ruột thì đó mới là sai lầm lớn nhất","Hảo thoại Trung Hoa");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạc nhược là khuyết điểm độc nhất mà người ta khó bề sửa được","La Rochefoucauld");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta luôn sợ phải bắt đầu một cái gì mới mà chúng ta rất muốn làm cho thật tốt, thật đúng, và cũng thật nghiêm túc","Brenda Ueland");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỉ muốn thôi chưa đủ mà cần phải hành động","Johann Wolfgang von Goethe");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không phải cứ mặc áo đẹp vào là người tử tế","Ngạn ngữ Pháp");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tiền bạc và thời gian là những gánh nặng ghê gớm nhất của cuộc đời... và những kẻ bất hạnh nhất là những người sở hữu chúng nhiều hơn mình có thể sử dụng","Samuel Johnson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Với người nghĩ rằng tiền có thể làm được mọi thứ, ta có thể nghi ngờ anh ta làm mọi thứ vì tiền","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi vấn đề là về tiền bạc, tất cả đều có chung một tôn giáo như nhau","Voltaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người ta thường cẩn thận với tiền bạc của mình hơn là các nguyên tắc của mình","Ralph Waldo Emerson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có ba người bạn trung thành: một người vợ tấm cám, một con chó nuôi từ bé và một số tiền dự trữ","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thu nhập cao là công thức tốt nhất cho hạnh phúc mà tôi từng biết","Jane Austen");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người ta giàu vì biết lao động, giàu hơn nữa vì biết tiết kiệm chi tiêu","Ngạn ngữ Thổ Nhĩ Kỳ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy cẩn thận với những chi phí nhỏ. Một lỗ rò bé có thể làm đắm cả con tàu","Tăng Quốc Phiên");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tài sản lớn nhất của bạn là khả năng kiếm tiền. Tài nguyên lớn nhất của bạn là thời gian","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cuộc đời đã ngắn ngủi như vậy mà chúng ta vẫn rút ngắn nó thêm khi bất cẩn lãng phí thời gian","Victor Hugo");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nỗi buồn bay đi trên đôi cánh của thời gian","La Fontaine");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thời gian thay đổi tất cả, chỉ trừ thứ bên trong chúng ta luôn luôn khiến ta thấy ngạc nhiên vì thay đổi","Thomas Hardy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Anh có thể trì hoãn, nhưng thời gian thì không","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thời gian đã mất không bao giờ tìm lại được","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thời gian là vàng bạc","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Anh có yêu cuộc sống không? Vậy đừng lãng phí thời gian, vì đó là chất liệu của cuộc sống","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta không nên nói một giờ của người này đáng giá với một giờ của người khác, mà nên nói người này trong một giờ cũng đáng giá như người khác trong một giờ. Thời gian là tất cả, con người không là gì: nhiều nhất cũng chỉ là thân xác của thời gian","Karl Marx");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự khác biệt giữa quá khứ, hiện tại và tương lai chỉ là một ảo tưởng dai dẳng đến ngoan cố","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đổi mới không phải là việc bạn bỏ ra bao nhiêu tiền cho nghiên cứu và phát triển. Khi Apple tung ra sản phẩm Mac, IBM tiêu tốn tiền R&D hơn ít nhất 100 lần. Đây không phải là vấn đề tiền bạc. Đây là về chuyện bạn có những con người như thế nào, bạn được lãnh đạo như thế nào, và bạn đạt được đến đâu.","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Vấn đề với cuộc đua mở kinh doanh trên Internet không phải là việc quá nhiều người mở công ty; đó là việc quá nhiều người không theo đuổi đến cùng. Đó là điều có thể hiểu được ở mức độ nào đó, bởi có quá nhiều thời khác tràn ngập tuyệt vọng và đau đớn, khi bạn phải sa thải nhân viên và hủy bỏ nhiều việc và đối mặt với những tình huống đặc biệt khó khăn. Đó là lúc bạn biết được mình là ai và giá trị của mình là gì","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để biến những ý tưởng thú vị trở thành hiện thực và những công nghệ còn non yếu thành một công ty có thể tiếp tục đổi mới trong nhiều năm trời, ta cần nhiều kỷ luật","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Anh không thể chỉ hỏi khách hàng xem họ muốn gì và rồi cố đem nó cho họ. Tới lúc anh hoàn thiện nó, họ đã muốn thứ mới mẻ khác rồi","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hệ thống là không có hệ thống nào. Điều đó không có nghĩa là chúng tôi không có quy trình. Apple là một công ty rất có tính kỷ luật, và chúng tôi có những quy trình tốt. Nhưng vấn đề không phải như vậy. Quy trình khiến bạn hoạt động hữu hiệu hơn","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Và điều đó đến từ việc nói không với 1000 thứ để chắc chắn chúng tôi không đi sai đường hay cố gắng làm quá nhiều. Chúng tôi luôn nghĩ về những thị trường mới mình có thể bước vào, nhưng chỉ bằng cách nói không bạn mới có thể tập trung vào những điều thật sự quan trọng","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi tự hào vì những gì chúng tôi không làm cũng như tôi tự hào vì những gì chúng tôi đã làm","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mô hình kinh doanh của tôi là ban nhạc The Beatles: Họ là bốn chàng trai có thể kiểm soát những khuynh hướng tiêu cực của nhau, họ cân bằng lẫn nhau. Và tổng số quan trọng hơn những phần rời rạc. Những điều lớn lao trong kinh doanh không được thực hiện bởi một người mà bởi một nhóm người","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Anh muốn bỏ phần còn lại của cuộc đời mình đi bán nước đường hay anh muốn có cơ hội thay đổi thế giới? - Câu hỏi nổi tiếng của Steve Jobs dành cho John Sculley, giám đốc trước của Apple","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn càng tìm kiếm sự bảo đảm, bạn càng ít có nó. Nhưng bạn càng tìm kiếm cơ hội, bạn càng có thể đạt được sự bảo đảm mà mình muốn","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thành công hay thất bại trong kinh doanh là do thái độ trong suy nghĩ nhiều hơn là khả năng suy nghĩ","Sir Walter Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những nhà lãnh đạo kinh doanh tốt tạo ra tầm nhìn, xác định rõ tầm nhìn, mạnh mẽ nắm lấy tầm nhìn và không ngừng thúc đẩy nó tới khi hoàn thiện","Thomas Hardy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cái gì không bán được thì tôi không muốn sáng chế. Doanh số là bằng chứng về tính hữu dụng, và tính hữu dụng là thành công","Thomas Edison");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn có thể lừa một vài người trong tất cả mọi lần và bạn có thể lừa mọi người trong một vài lần, nhưng bạn không thể lừa mẹ","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ngôi nhà không phải là mái ấm trừ khi nó chứa thức ăn và lửa cho tâm hồn cũng như cơ thể","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không ai có thể hiểu những đau khổ của tôi, hay nỗi kinh hoàng dâng lên trong lồng ngực, nếu người đó không hiểu trái tim của một người mẹ","Marie Antoinette");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi bạn là một người mẹ, bạn không bao giờ thực sự cô độc trong suy nghĩ của mình. Một người mẹ luôn phải nghĩ hai lần, một lần cho bản thân và một lần cho con cái","Sophia Loren");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trái tim của người mẹ là vực sâu muôn trượng mà ở dưới đáy, bạn sẽ luôn tìm thấy sự tha thứ","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người học trò luôn luôn bắt đầu bằng cách tìm ra khiếm khuyết, nhưng nhà học giả thấy ưu điểm trong mọi thứ","Georg Wilhelm Friedrich Hegel");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giáo dục là nghệ thuật biến con người thành có đạo đức","Georg Wilhelm Friedrich Hegel");
		danhNgonList.add(dn);
		dn = new DanhNgon("Với nhân dân, quyền lực duy nhất là pháp luật; với cá nhân, quyền lực duy nhất là lương tâm","Victor Hugo");
		danhNgonList.add(dn);
		dn = new DanhNgon("Pháp luật là đạo đức biển hiện ra bên ngoài, đạo đức là pháp luật ẩn giấu bên trong","Abraham Lincoln");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng phấn đấu để thành công mà hãy phấn đấu để mình có ích","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nhà trường chỉ cho chúng ta chiếc chìa khóa tri thức, học trong cuộc sống là công việc cả đời","Bill Gates");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nơi không có quyền lực cộng đồng thì không có pháp luật, nơi không có pháp luật thì không có gì gọi là công bằng","O. Wendell Holmes");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi thà sống cả đời tin có thần linh và rồi chết mà phát hiện hoàn toàn không có, còn hơn sống cả đời không tin tưởng và rồi chết mà phát hiện có thần linh","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình bạn, cũng như tình yêu, bị phá hủy bởi sự xa cách kéo dài, dù nó có thể trở nên mạnh mẽ hơn nhờ những xa cách ngắn","Samuel Johnson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không biết đã bao nhiêu lần con người buông tay từ bỏ khi mà chỉ một chút nỗ lực, một chút kiên trì nữa thôi là anh ta sẽ đạt được thành công","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thêm một chút bền bỉ, một chút nỗ lực, và điều tưởng chừng như là thất bại vô vọng có thể biến thành thành công rực rỡ","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ranh giới giữa thành công và thất bại nhỏ tới mức chúng ta hiếm khi biết được mình đã vượt qua nó khi nào: nhỏ tới mức chúng ta thường đứng trên nó mà không ý thức được","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi chưa thất bại. Tôi chỉ là đã tìm ra 10,000 cách không hoạt động","Thomas Edison");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để có bạn bè, đầu tiên chúng phải là một người bạn đã","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn bè là những người biết rõ về bạn mà vẫn yêu bạn","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một cái máy có thể làm công việc của năm mươi người bình thường. Không có máy móc nào có thể làm được việc của một người phi thường","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kẻ học giả không lo không có tài, chỉ lo không có chí","Trung Luận");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng bao giờ chờ đợi một người thật hoàn hảo, vì rằng không có ai hoàn hảo cả, và cũng vì rằng chỉ khi bạn yêu họ, họ mới trở nên hoàn hảo mà thôi!","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai quên hạnh phúc của mình để đi tìm hạnh phúc cho người khác, sẽ gặp hạnh phúc của mình tràn đầy","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu là một con vật quái dị: để nó đói khát thì nó sống mãi, cho nó no nê thì nó chết mất","Alfred De Musset");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thỏa mãn không phải là không đổ thêm dầu, mà là dập tắt đi ít lửa","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nụ hôn đầu hoàn toàn không thể bảo đảm cho tình yêu vĩnh cửu, nhưng nó lại là một dấu ấn mãi không phai trong lịch sử cuộc đời","Byron");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu và hạnh phúc như hình với bóng. Nếu biết bảo vệ tình yêu thì hạnh phúc sẽ thành sự thật, ngược lại nếu không biết bảo vệ tình yêu thì hạnh phúc sẽ là một ảo tưởng","Blaise Pascal");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng sợ thất bại. Lần thất bại thứ nhất cần phải có, vì nhờ đó mà ý chí ta thêm cứng cáp. Lần thất bại thứ hai có thể có ích. Bị bại lần thứ ba mà vẫn đứng vững, con người đó như chùm nho chín ở trên đá sỏi: không có thứ nho nào ngọt hơn thế nữa","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có thể thấy được tính cách của một người qua cách anh ta nói chuyện","Menander");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tính cách là kết quả của hai thứ: thái độ tinh thần và cách chúng ta sử dụng thời gian","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để thành công trong cuộc sống, bạn cần hai thứ: sự ngu dốt và lòng tự tin","Mark Twain");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thành công không phải là chìa khóa mở cánh cửa hạnh phúc. Hạnh phúc là chìa khóa dẫn tới cánh cửa thành công. Nếu bạn yêu điều bạn đang làm, bạn sẽ thành công","Albert Schweitzer");
		danhNgonList.add(dn);
		dn = new DanhNgon("Vì sao chúng ta lại nhắm mắt khi ngủ, khi khóc, khi tưởng tượng, khi hôn nhau, khi cầu nguyện? Bởi vì những gì đẹp nhất trên thế gian này chẳng thể nào nhìn thấy bằng mắt mà phải được cảm nhận bằng con tim","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sức mạnh không đến từ thể chất. Nó đến từ ý chí bất khuất","Mahatma Gandhi");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy học từ sai lầm của người khác. Bạn sẽ không bao giờ sống đủ lâu để phạm phải tất cả sai lầm","Groucho Marx");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có người nói rằng hôn nhân cản trở sự lãng mạn. Không nghi ngờ gì. Mỗi khi bạn có một cuộc lãng mạn, thế nào vợ bạn cũng sẽ can thiệp","Groucho Marx");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy chọn vợ bằng tai hơn là bằng mắt","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nơi nào có hôn nhân mà không có tình yêu, ở đó xuất hiện tình yêu mà không có hôn nhân","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một cuộc hôn nhân tốt là giữa bà vợ mù và ông chồng điếc","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự tưởng tượng của phụ nữ diễn ra rất nhanh chóng; nó nhảy từ thán phục sang tình yêu, rồi từ tình yêu sang hôn nhân chỉ trong khoảng khắc","Jane Austen");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không người đàn ông nào nên lấy vợ cho tới khi đã học giải phẫu và mổ xẻ ít nhất là một người phụ nữ","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một người chồng tốt không bao giờ đi ngủ trước vào buổi đêm và dậy sau vào buổi sáng","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy để người vợ khiến chồng mình vui vẻ trở về nhà, và hãy để người chồng khiến nàng nuối tiếc khi mình rời nhà","Martin Luther");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta không cười vì chúng ta hạnh phúc - chúng ta hạnh phúc vì chúng ta cười","William James");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hành động có thể không mang tới hạnh phúc, nhưng không có hạnh phúc nào lại thiếu hành động","William James");
		danhNgonList.add(dn);
		dn = new DanhNgon("Vì bạn nhận được nhiều niềm vui hơn khi đem niềm vui cho người khác, bạn nên suy nghĩ nhiều về niềm hạnh phúc bạn có thể cho","Eleanor Roosevelt");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cứ mỗi ngày tôi lại càng tin rằng sự lãng phí cuộc đời nằm trong những tình cảm chúng ta không cho đi, sức mạnh chúng ta không sử dụng, sự thận trọng ích kỷ không dám mạo hiểm điều gì và lẩn tránh nỗi đau, cũng đồng thời để lỡ hạnh phúc","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cuộc sống làm bạn buồn chán ư? Hãy lao vào công việc bạn tin tưởng bằng tất cả trái tim, sống vì nó, chết vì nó, và bạn sẽ tìm thấy thứ hạnh phúc tưởng chừng như không bao giờ đạt được","Dale Carnegie");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự thông minh hay trí tưởng tượng ngất trời, hay thậm chí cả hai kết hợp cùng nhau cũng không làm nên thiên tài. Yêu thương, yêu thương, yêu thương, đó là linh hồn của một thiên tài","Wolfgang Amadeus Mozart");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi tôi 17 tuổi, tôi đã đọc được một câu trích dẫn: “Nếu bạn sống mỗi ngày như thể đó là ngày cuối cùng của bạn, một ngày nào đó, bạn sẽ đúng”. Câu nói ấy đã thực sự tạo được ấn tượng với tôi, và kể từ đó, 33 năm qua, tôi đã nhìn vào gương mỗi buổi sáng và tự hỏi mình: “Nếu hôm nay là ngày cuối cùng của đời mình, thì tôi có muốn làm những điều mình sẽ làm hôm nay không?”. Và bất cứ khi nào câu trả lời là: “không” trong nhiều ngày liên tiếp, tôi biết tôi cần phải thay đổi","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta không có cơ hội làm quá nhiều điều, và mỗi thứ chúng ta làm đều phải thật sự tuyệt vời. Bởi vì đây là cuộc đời của chúng ta. Cuộc đời ngắn ngủi lắm, và rồi bạn chết, bạn biết chứ? Và chúng ta đều được lựa chọn để làm điều này với cuộc đời mình. Vì vậy điều ta làm nên thật tốt. Nên đáng giá","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thời gian của bạn không nhiều, vì vậy đừng lãng phí nó để sống cuộc đời của người khác. Đừng nghe những lời giáo điều - đó là sống với kết quả suy nghĩ của người khác. Đừng để âm thanh của những quan điểm khác lấn át đi giọng nói bên trong bạn. Và quan trọng nhất, hãy giữ lấy sự can đảm để đi theo trái tim và trực giác. Chúng biết bạn thực sự muốn trở thành con người như thế nào. Mọi thứ khác chỉ là thứ yếu","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy sống như ngày mai anh chết. Hãy học như anh sẽ sống mãi mãi","Mahatma Gandhi");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy sống khát khao, hãy sống dại khờ","Steve Jobs");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để hiểu được sắc đẹp của một bông tuyết, cần phải đứng ra giữa trời lạnh","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nếu một người đổ hết ví vào đầu, không ai có thể cướp được nó khỏi anh ta","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng để trường lớp cản trở con đường giáo dục của bạn","Mark Twain");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ta có thể nói rằng bí ẩn vĩnh cửu của thế giới này chính là sự lĩnh hội","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học từ ngày hôm qua, sống ngày hôm nay, hi vọng cho ngày mai. Điều quan trọng nhất là không ngừng đặt câu hỏi","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học... học để là chính mình, và học để từ bỏ với vẻ thanh cao những gì không phải là mình","Henri Frederic Amiel");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sáu mươi năm trước tôi biết mọi thứ; giờ tôi chẳng biết gì cả; giáo dục là cuộc khám phá không ngừng về sự ngu dốt của chúng ta","Will Durant");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người dạy học phải tin vào sức mạnh tiềm tàng của học trò, và anh ta phải nỗ lực hết sức để giúp học trò mình trải nghiệm được sức mạnh này","Alfred Adler");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có hai kiểu giáo dục. Một kiểu dạy chúng ta làm thế nào để sống, và kiểu còn lại dạy chúng ta phải sống như thế nào","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cố gắng làm ai đó yêu bạn cũng khó như cố lựa chọn người để yêu","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta bảo tình yêu là sự sống; nhưng tình yêu không có hy vọng và niềm tin là cái chết đau đớn","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu thật sự đã hiếm, tình bạn thật sự còn hiếm hơn","La Fontaine");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự thật là... Chúng ta trốn vì muốn được tìm thấy. Chúng ta bỏ đi vì muốn biết ai sẽ theo mình. Chúng ta khóc để xem ai sẽ lau đi giọt lệ. Và chúng ta để trái tim tan vỡ, muốn thấy ai sẽ đến và chữa lành trái tim ta","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu đến dù bạn muốn hay không. Đừng cố điều khiển nó!","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỉ mất 3 giây để nói lời yêu, nhưng phải mất cả cuộc đời để chứng minh điều đó","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi sẽ không hy sinh tình yêu, tình yêu thật sự, cho bất cứ con điếm hay bạn hữu nào, hay công việc nào, bởi cuối cùng thì bạn ở một mình trong đêm","John Lennon");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khoái cảm nhục dục sẽ trôi qua và biến mất, nhưng tình bạn giữa chúng ta, sự tin tưởng lẫn nhau, niềm vui sướng của con tim, sự say mê của tâm hồn, những điều này không tan đi và không thể bị phá hủy","Voltaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng bao giờ tạm biệt khi bạn vẫn còn muốn thử, đừng bao giờ từ bỏ nếu bạn vẫn cảm thấy mình làm được. Đừng bao giờ nói mình không còn yêu người đó nữa nếu bạn không thể buông tay","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nếu bạn yêu ai đó, hãy để họ ra đi. Nếu họ trở lại, họ sẽ luôn thuộc về bạn. Nếu họ không trở lại, họ chưa từng thuộc về bạn","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu là khi bạn rơi lệ và vẫn muốn anh, là khi anh lờ bạn đi và bạn vẫn yêu anh, là khi anh yêu người con gái khác nhưng bạn vẫn cười và bảo em mừng cho anh, khi mà tất cả những gì bạn thực sự muốn làm là khóc","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi anh đi câu tình yêu, hãy lấy trái tim làm mồi chứ đừng lấy bộ não","Mark Twain");
		danhNgonList.add(dn);
		dn = new DanhNgon("Độ lâu bền của sự đam mê tỉ lệ thuận với sự kháng cự ban đầu của người phụ nữ<br/>","Honoré De Balzac");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng đếm những gì bạn đã mất, hãy quý trọng những gì bạn đang có và lên kế hoạch cho những gì sẽ đạt được bởi quá khứ không bao giờ trở lại, nhưng tương lai có thể bù đắp cho mất mát","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mong tình yêu ẩn dấu sâu trong tim bạn tìm thấy tình yêu chờ đợi bạn trong mơ. Mong nụ cười bạn tìm thấy ở ngày mai xóa đi nỗi đau tìm trong quá khứ","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người lạc quan là người nhìn đâu cũng thấy đèn xanh còn người bi quan thấy khắp nơi chỉ toàn đèn đỏ... kẻ thực sự khôn ngoan thì mù màu","Albert Schweitzer");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cái ngày đen tối nhất rồi cũng sẽ trôi qua nếu bạn sống tới ngày mai","William Cowper");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để thật sự cười, anh phải có thể lấy nỗi đau của mình ra và chơi với nó!","Charlie Chaplin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trước 48 tuổi, người bi quan là người biết quá nhiều; nếu quá tuổi đó mà vẫn lạc quan, anh ta biết quá ít","Mark Twain");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lòng quyết tâm vô hình có thể tựu thành hầu như mọi thứ, và trong nó chính là sự khác biệt giữa vĩ nhân và kẻ tầm thường","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một trong những bằng chứng rõ nét nhất cho tình bạn mà một người có thể dành cho người khác là nhẹ nhàng nói với bạn mình khuyết điểm của anh ta. Nếu có thứ gì hơn thế thì đấy chính là lắng nghe với sự biết ơn và sửa chữa sai lầm đó","Edward Bulwer Lytton");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy hiểu điều mình muốn làm, giữ vững ý nghĩ đó trong đầu, và hàng ngày hãy làm điều cần làm, và mỗi hoàng hôn, bạn sẽ thấy mình tới gần mục tiêu hơn","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nếu bạn đặt mục tiêu và theo đuổi chúng với tất cả lòng quyết tâm, tài năng sẽ đưa bạn tới những nơi khiến bạn phải ngạc nhiên","Les Brown");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có thật ít người đủ can đảm để thừa nhận sai lầm của chính mình, hay đủ quyết tâm để sửa chữa chúng","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gieo hành động, bạn sẽ gặt thói quen, gieo thói quen bạn sẽ gặt cá tính, gieo cá tính bạn sẽ gặt số phận","Napoleon Hill");
		danhNgonList.add(dn);
		dn = new DanhNgon("Muốn đi tới mục tiêu lớn phải bắt đầu từ mục tiêu nhỏ","Lenin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không ai xứng đáng với những giọt nước mắt của bạn, nhưng nếu có người xứng đáng, anh ta sẽ không làm bạn khóc","Gabriel Garcia Marquez");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kỹ năng, chứ không phải sức mạnh, điều khiển con tàu","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Với lương tâm, quy luật của số đông không có tác dụng","Mahatma Gandhi");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một nụ hôn phá tan khoảng cách giữa tình bạn và tình yêu","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu đến với những ai vẫn hy vọng dù đã từng thất vọng, vẫn tin tưởng dù từng bị phản bội, vẫn yêu thương dù từng bị tổn thương","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Với thế giới, bạn có thể chỉ là một người, nhưng với một người, bạn có thể là cả thế giới","Khuyết Danh");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng bao giờ giải thích; bạn bè thật sự không cần nó, và kẻ thù đằng nào cũng chẳng tin bạn đâu","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một trong những điều sung sướng của bạn cũ là bạn có thể ngu ngốc khi ở bên họ","Ralph Waldo Emerson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một người bạn trung thành là tuyến phòng thủ mạnh mẽ; và người tìm thấy anh ta đã tìm thấy một báu vật","Louisa May Alcott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sách hay, cũng như bạn tốt, ít và được chọn lựa; chọn lựa càng nhiều, thưởng thức càng nhiều","Louisa May Alcott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Vết thương của tình yêu chỉ có thể chữa lành bởi người gây ra chúng","Publilius Syrus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người hạnh phúc là người lắng nghe; kẻ bất hạnh là kẻ thổ lộ","Ralph Waldo Emerson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kẻ phạm vào tội lỗi là con người; đau buồn vì nó là thánh nhân; kiêu hãnh về nó là ác quỷ","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình bạn nhân lên niềm vui và chia bớt đau buồn","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình bạn thì hiếm, nhưng bạn bè thì không hiếm","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lí lẽ của người nghèo thường không được nghe thấy","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người không hy vọng điều tốt đẹp không sợ hãi điều xấu xa","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lòng quyết tâm vô hình có thể tựu thành hầu như mọi thứ, và trong nó chính là sự khác biệt giữa vĩ nhân và kẻ tầm thường","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hôm nay là học trò của hôm qua","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự trả thù cao quý nhất chính là tha thứ","Thomas Fuller");
		danhNgonList.add(dn);
		dn = new DanhNgon("Điều kiện tất yếu đầu tiên cho hạnh phúc của nhân dân là sự bãi bỏ tôn giáo","Karl Marx");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôn giáo là thuốc phiện của nhân dân","Karl Marx");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người nói càng nhiều càng tạo ra nhiều nhầm lẫn","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Phải làm nhiều việc tốt mới gây được tiếng tăm tốt, và chỉ một việc xấu ta có thể đánh mất nó","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một cuộc đời thoải mái và một cuộc đời lười biếng là hai chuyện khác nhau. Khi xuống mồ rồi sẽ tha hồ mà ngủ","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người lao động là người hạnh phúc. Chính người nhàn rỗi mới là người khốn khổ","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai là người giàu có? Đó là người biết vui mừng với phần của mình","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thiên tài không có học hành giống như bạc trong mỏ","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Người khoe khoang vợ và ví tiền quá thường xuyên có nguy cơ phải đem cho mượn cả hai","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy chậm rãi khi chọn bạn, và càng chậm hơn khi thay bạn","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có những người chết ở tuổi 25 và chỉ đến 75 tuổi mới được chôn","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dối trá và lừa lọc là hành động của kẻ ngu xuẩn không có đủ trí óc để trung thực","Benjamin Franklin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không phải là tôi quá thông minh, chỉ là tôi chịu bỏ nhiều thời gian hơn với rắc rối","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi không bao giờ tin vào vị Chúa chơi xúc xắc với thế gian này","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chỉ có hai điều là vô hạn: vũ trụ và sự ngu xuẩn của con người, và tôi không chắc lắm về điều đầu tiên","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kẻ ngu xuẩn nào cũng có thể khiến mọi thứ trở nên to hơn, phức tạp hơn và bạo lực hơn. Chỉ bàn tay của thiên tài - và thật nhiều dũng khí - để biến chuyển ngược lại","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúa luôn chọn cách đơn giản nhất","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có một câu hỏi đôi khi khiến tôi thấy mơ hồ: Tôi điên hay người khác điên?","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự đơn điệu và cô độc của một cuộc sống yên lặng kích thích trí sáng tạo","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Logic sẽ đưa anh từ điểm A tới điểm B. Trí tưởng tượng sẽ đưa anh tới mọi nơi","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Sự khác biệt giữa thiên tài và kẻ ngu dốt là ở chỗ thiên tài luôn có giới hạn<br/>","Albert Einstein");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta hãy dịu dàng và tử tế nâng niu những phương tiện của tri thức. Chúng ta hãy dám đọc, nghĩ, nói và viết","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trí óc già nua cũng như những chú ngựa già nua; bạn phải để chúng luyện tập nếu bạn muốn chúng hoạt động được tốt","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thế giới không có tôn giáo hẳn sẽ là thế giới tốt đẹp nhất có thể có được","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy để trí óc con người tự do. Nó phải được tự do. Nó sẽ được tự do. Sự mê tín và giáo điều không thể giam cầm được nó","John Adams");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hận thù và bạo lực không thể chỉ ở trong một phần của thế giới mà không gây ảnh hưởng lên phần còn lại","Eleanor Roosevelt");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con người trưởng thành qua kinh nghiệm nếu họ đối diện với cuộc đời trung thực và can đảm. Đây là cách tính cách hình thành","Eleanor Roosevelt");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta trở nên mạnh mẽ, từng trải và tự tin nhờ nhờ từng trải nghiệm mà chúng ta thực sự dừng lại để nhìn thẳng vào mặt nỗi sợ... chúng ta phải làm điều mà chúng ta nghĩ mình không thể","Eleanor Roosevelt");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thiên tài một phần trăm là cảm hứng và chín mươi chín phần trăm là mồ hôi","Thomas Edison");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi chưa bao giờ vô tình làm điều gì, cũng như không phát minh nào của tôi đến từ sự vô tình; chúng đến từ lao động","Thomas Edison");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi tìm thấy lạc thú lớn nhất, và cũng như phần thưởng, nằm trong công việc vượt qua điều mà thế giới gọi là thành công","Thomas Edison");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi cảm ơn Chúa đã độ lượng ban cho mình cơ hội để hiểu rằng cái chết là chìa khóa mở cánh cửa dẫn tới chân hạnh phúc","Wolfgang Amadeus Mozart");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chìa khóa thành công là tập trung lý trí của chúng ta vào những điều chúng ta muốn chứ không phải những điều chúng ta sợ","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Những người thành công luôn luôn tìm kiếm cơ hội để giúp đỡ người khác. Những người không thành công luôn luôn hỏi, Tôi được lợi gì?","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tất cả những người đàn ông và phụ nữ thành công đều là những người mơ mộng. Họ mơ mộng về tương lai của họ, lý tưởng trên mọi phương diện, và rồi họ lao động mỗi ngày hướng về viễn cảnh xa xôi ấy, mục tiêu hay cái đích đó","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mục đích của người viết văn là giữ cho nền văn minh không tự hủy diệt","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi chỉ còn lại một ít thời gian, và tôi không muốn lãng phí nó cho Chúa","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta tiếp tục hình thành tính cách trong cả cuộc đời. Nếu chúng ta hoàn toàn hiểu rõ bản thân mình, chúng ta nên chết đi cho rồi","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng đi trước tôi; tôi có thể sẽ không theo. Đừng đi sau tôi; tôi có thể sẽ không dẫn lối. Hãy đi bên cạnh và trở thành bạn của tôi","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi tiếp tục tin rằng thế giới này không có ý nghĩa tối hậu nào. Nhưng tôi biết rằng có điều gì đó có ý nghĩa, và đó là con người, bởi anh ta là sinh vật duy nhất khăng khăng đi tìm ý nghĩa","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Rất bình thường khi cho đi một phần nhỏ cuộc đời để không đánh mất nó toàn bộ","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Điều vô lý là khái niệm thiết yếu và là sự thật đầu tiên","Albert Camus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi thích đi dưới mưa để không ai thấy tôi đang khóc","Charlie Chaplin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để thật sự cười, anh phải có thể lấy nỗi đau của mình ra và chơi với nó!","Charlie Chaplin");
		danhNgonList.add(dn);
		dn = new DanhNgon("Khi nghĩ về những người bạn đồng hành đã rời ta, chúng ta cảm thấy cô đơn gấp đôi","Sir Walter Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một cái đầu tỉnh táo, một trái tim trung thực và một linh hồn khiêm nhường, đó là ba người dẫn đường tốt nhất qua thời gian và cõi vĩnh hằng","Sir Walter Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Để thành công, thái độ cũng quan trọng ngang bằng khả năng","Sir Walter Scott");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tiếng cười là mặt trời đuổi mùa đông khỏi gương mặt con người","Victor Hugo");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tương lai có rất nhiều tên: Với kẻ yếu, nó là Điều không thể đạt được. Đối với người hay sợ hãi, nó là Điều chưa biết. Với ai dũng cảm, nó là Cơ hội","Victor Hugo");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đừng bao giờ vung lưỡi hái vào ruộng ngô người khác","Publilius Syrus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi thường hối tiếc vì những gì mình nói, chứ không bao giờ vì sự im lặng của mình","Publilius Syrus");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không gì nguy hiểm hơn bạn bè ngu dốt; tôi thà có kẻ thù khôn","La Fontaine");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chúng ta phải cười trước khi ta hạnh phúc, bởi nỗi sợ rằng ta sẽ chết trước khi ta kịp cười","La Fontaine");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nước mắt là ngôn ngữ câm lặng của đau buồn","Voltaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi đã sống tám mươi năm trong đời và tôi chẳng biết điều gì, ngoài việc cam chịu và tự bảo mình rằng côn trùng sinh ra là để cho nhện nuốt lấy, và con người sinh ra để bị tàn phá bởi sự đau khổ","Voltaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mê tín dị đoan đối với tôn giáo cũng giống như chiêm tinh học đối với thiên văn học, đứa con gái điên dại của bà mẹ thông minh. Những đứa con gái này đã thống trị thế giới quá lâu","Voltaire");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn từ đâu tới không quan trọng. Tất cả những gì quan trọng là bạn đang đi đâu","Brian Tracy");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cuộc sống trở nên khó khăn hơn khi chúng ta sống vì người khác, nhưng nó cũng trở nên đẹp đẽ và hạnh phúc hơn","Albert Schweitzer");
		danhNgonList.add(dn);
		dn = new DanhNgon("Hãy đếm tuổi của bạn bằng số bạn bè chứ không phải số năm. Hãy đếm cuộc đời bạn bằng nụ cười chứ không phải bằng nước mắt","John Lennon");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bạn càng trở nên thật, mọi thứ khác càng trở nên không thật","John Lennon");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thời gian mà bạn hưởng thụ để phung phí, không lãng phí","John Lennon");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình yêu lớn lên nhờ cho đi. Sự yêu thương mà chúng ta cho đi là sự yêu thương duy nhất mà chúng ta giữ được","Elbert Hubbard");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tình bạn là Tình yêu không có cánh!","Byron");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tôi chẳng có gì để làm với quá khứ; với tương lai cũng vậy. Tôi sống trong hiện tại","Ralph Waldo Emerson");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai ơi bưng bát cơm đầy <br/>Dẻo thơm một hạt, đắng cay muôn phần","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai ơi chẳng chóng thì chầy <br/>Có công mài sắt, có ngày nên kim","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai ơi đừng bỏ ruộng hoang <br/>Bao nhiêu tấc đất tấc vàng bấy nhiêu","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Anh em bốn bể là nhà <br/>Người dưng khác họ vẫn là anh em","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cá không ăn muối cá ươn <br/>Con cãi cha mẹ trăm đường con hư","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cái răng cái tóc là góc con người","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cái nết đánh chết cái đẹp","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chim khôn kêu tiếng rảnh rang <br/>Người khôn nói tiếng dịu dàng dễ nghe","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chim quyên ăn trái nhãn lồng <br/>Lia thia quen chậu, vợ chồng quen hơi","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chim trời ai dễ đếm lông <br/>Nuôi con ai dễ kể công tháng ngày","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con hơn cha là nhà có phúc","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con không cha như nhà không nóc <br/>Con không mẹ con khóc tối ngày","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con không chê cha mẹ khó <br/>Chó không chê chủ nhà nghèo","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con người có tổ có tông <br/>Như cây có cội, như sông có nguồn","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con sâu làm rầu nồi canh <br/>Một người làm xấu, nhơ danh cả nhà","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con vua thì được làm vua <br/>Con sãi ở chùa thì quét lá đa","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có cha có mẹ thì hơn <br/>Không cha không mẹ như đờn đứt dây","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có làm thì mới có ăn <br/>Ngồi không ai dễ đem phần tới cho","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Công cha như núi Thái Sơn <br/>Nghĩa mẹ như nước trong nguồn chảy ra <br/>Một lòng thờ mẹ kính cha <br/>Cho tròn chữ hiếu mới là đạo con","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cờ bạc là bác thằng bần <br/>Cửa nhà bán hết, tra chân vào cùm","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dạy con từ thuở còn thơ <br/>Dạy vợ từ thuở bơ vơ mới về","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dao sắc không gọt được chuôi","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dã tràng xe cát biển đông <br/>Nhọc nhằn mà chẳng nên công cán gì","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đói lòng ăn hạt chà là <br/>Để cơm nuôi mẹ, mẹ già yếu răng","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đói lòng ăn nắm lá sung <br/>Chồng một thì lấy, chồng chung thì đừng","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đời cha ăn mặn đời con khát nước","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giặc đến nhà, đàn bà phải đánh","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gió mùa thu mẹ đưa con ngủ <br/>Năm canh dài thức đủ năm canh","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giọt máu đào hơn ao nước lã","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gieo gió gặp bão","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giỏ nhà ai quai nhà nấy","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chớp đông nhay nháy, gà gáy thì mưa<br/>Tháng ba mưa đám, tháng tám mưa cơn","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ếch kêu uôm uôm, ao chuôm đầy nước","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kính trên nhường dưới","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Kính già, già để tuổi cho","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Không thầy đố mày làm nên","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nhân chi sơ tính bổn thiện","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chết vinh còn hơn sống nhục","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tháng bảy heo may, chuồn chuồn bay thì bão","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thức lâu mới biết đêm dài<br/>Ở lâu mới biết là người có nhân","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thứ nhất thì tu tại gia<br/>Thứ nhì tu chợ, thứ ba tu chùa","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thuyền ơi có nhớ bến chăng<br/>Bến thì một dạ khăng khăng nhớ thuyền","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trai khôn kén vợ chợ đông<br/>Gái khôn tìm chồng giữa chốn ba quân","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trúc xinh trúc mọc bờ ao<br/>Em xinh em đứng chỗ nào cũng xinh","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tất cả hoa quí trên đời<br/>Không bằng hai tiếng mỉm cười mẹ cha","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Thương nhau mấy núi cũng trèo<br/>Mấy sông cũng lội, mấy đèo cũng qua","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tiên học lễ, hậu học văn","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nói lời phải giữ lấy lời<br/>Đừng như con bướm đậu rồi lại bay","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Tháp Mười đẹp nhất hoa sen<br/>Việt nam đẹp nhất có tên Bác Hồ","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trẻ cậy cha, già cậy con","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Miếng ngon nhớ lâu, đòn đau nhớ đời","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mẹ cha là biển là Trời<br/>Làm con sao dám cãi lời mẹ cha","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mẹ còn chẳng biết là may<br/>Mẹ mất mới tiếc những ngày làm con","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Mẹ già như chuối chín cây<br/>Gió đưa mẹ rụng, con phải mồ côi","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ăn không nên đọi nói không nên lời","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Lúa chiêm nép ở đầu bờ, <br/>Hễ nghe tiếng sấm mở cờ mà lên","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Rủ nhau đi cấy, đi cày, <br/>Bây giờ khó nhọc có ngày phong lưu<br/>Trên đồng cạn dưới đồng sâu, <br/>Chồng cày vợ cấy con trâu đi bừa","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ai ơi đừng bỏ ruộng hoang, <br/>Bao nhiêu tấc đất tấc vàng bấy nhiêu","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Một cây làm chẳng nên non, <br/>Ba cây chụm lại thành hòn núi cao","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Bầu ơi thương lấy bí cùng<br/>Tuy rằng khác giống nhưng chung một giàn","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Giàu đâu những kẻ ngủ trưa <br/>Sang đâu đến kẻ say sưa tối ngày","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dù ai buôn đâu bán đâu <br/>Mồng mười tháng chín chọi trâu thì về","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Dù ai đi ngược về xuôi<br/>Nhớ ngày giỗ tổ mồng mười tháng ba","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đi một ngày đàng, học một sàng khôn","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học là học đạo làm người <br/>Con đừng lêu lổng kẻ cười người chê","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Làm trai cố chí học hành<br/>Lập nên công nghiệp để dành mai sau","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Con lên ba cả nhà học nói","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Học ăn học nói học gói học mở","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Nhân bất học bất tri lý<br/>Ngọc bất trác bất thành khí","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Cha mẹ sinh con, trời sinh tính","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Trời sinh voi, trời sinh cỏ","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Ở hiền thì lại gặp lành<br/>Những người nhân đức trời dành phước cho","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Có thờ có thiêng, có kiêng có lành","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Đêm đêm ra thắp đèn trời<br/>Cầu cho cha mẹ sống đời với con","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Chiều chiều ra đứng ngõ sau<br/>Trông về quê mẹ ruột đau chín chiều","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Gần mực thì đen, gần đèn thì sáng","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Yêu nhau cau sáu bổ ba,ghét nhau cau sáu bổ ra làm mười","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Yêu trẻ, trẻ đến nhà; kính già, già để phúc cho","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("Yêu nhau yêu cả đường đi, ghét nhau ghét cả tông chi họ hàng","Ca Dao Tục Ngữ");
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐỨC<br/>Dùng tấm lòng thánh thiện <br/>Hành xử với mọi người<br/>Thành tựu vị tha hạnh <br/>Đức ngạt ngào muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐỊNH<br/>Pha chén trà buổi sáng <br/>Mười phương thế giới thơm<br/>Định tuệ tâm viên mãn <br/>Tình đời hoa kết đơn",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐẠT<br/>Thông đạt đời như huyễn<br/>An nhiên với duyên trần<br/>Thu đông choàng thêm áo<br/>Xuân hạ chơi cùng trăng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CHÍ <br/>Chí thành đôi tay chắp <br/>Là đóa sen rạng ngời <br/>Dâng cúng mười phương Phật<br/>Hương lòng tỏa muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CHÂU <br/>Tâm hồn viên châu sáng<br/>Thanh lọc từng phút giây<br/>Ưu phiền không phát khỏi <br/>Tịnh độ tại nơi này",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CÁT<br/>Chuông vọng lạy sương  sớm<br/>Từng cánh mai chuyển mình<br/>Cát tường mùa lễ hội <br/>Nắng trải vàng trang kinh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("BÌNH ĐẲNG<br/>Không thị phi đen trắng <br/>Không cao thấp sang hèn<br/>Ta người đều bình đẳng<br/>Phật vị - một tòa sen",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("BẢO <br/>Của báu trên cõi đời<br/>Tấm lòng trải muôn nơi<br/>Trao nhau niềm tin sống<br/>Trao nhau những nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("AN NHIÊN<br/>Chiếc lá cuối chiều rơi <br/>Bụi trần nghe xao động <br/>Mặc đời bao con sóng<br/>Vẫn an nhiên nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("DUYÊN<br/>Bàn tay ta vun đắp<br/>Thành bại thuộc vào duyên<br/>Vinh nhục ai không gặp <br/>Có chi phải ưu phiền",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("GIÁC<br/>Triêu mộ lời chuông điểm <br/>Vơi tan bao niệm trần<br/>Hành hương về ánh sáng<br/>Thấy đất trời thanh tân",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HẰNG<br/>Rời khỏi vòng tay mẹ <br/>Trăng mười sáu vơi đầy<br/>Lời kinh cầu sớm tối<br/>Còn thơm hương tóc mây",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HẠNH <br/>Ngữ ngôn luôn chính trực <br/>Khiêm hạ ở tại lòng<br/>Hành xử như chính pháp<br/>Đạo đời đều thong dong",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HẬU<br/>Trái tim đầy nhân hậu<br/>Dung chứa bao tình người<br/>Biển cả vô bờ bến<br/>Ngại gì hòn bột trôi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HIẾU<br/>Vu lan lời kinh vọng <br/>Hoa trắng áo em cài<br/>Sen búp bàn tay nhỏ<br/>Sinh thành ơn khó phai",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HOA<br/>Xuân điểm sắc hồng tươi<br/>Đôi cành hoa ban sớm<br/>Trời xanh trong ai nhuộm<br/>Man mác một nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HÒA<br/>Buông thị phi nhân ngã<br/>Bỏ hơn thua bại thành<br/>Hòa theo từng nhịp thở<br/>Của đất trời thanh thanh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HOÀNG<br/>Tuệ giác thật huy hoàng<br/>Đoạn phiễn não thế gian<br/>Mùa thu cây trút lá<br/>Xuân đến nở hoa ngàn",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HỢP<br/>Cùng nhau xây dựng đời <br/>Chung tay kiến thiết đạo <br/>Nghĩa tình thơm hạt gạo<br/>Trắng trong bao nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HÙNG<br/>Hùng tâm phá phiền não<br/>Từ tâm hành muôn hạnh <br/>Nẻo ác nào xa lánh<br/>Đương thiện về an nhiên",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HƯƠNG<br/>Tay chạm hạt phù sa<br/>Hương sen về ngập lối<br/>Nâng từng trang lá bối<br/>Lời kinh lòng ngân nga",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HỮU – VÔ<br/>Ánh nguyệt dưới lòng sông<br/>Hữu – vô nào ai biết<br/>Dừng rồi niệm phân biệt<br/>Tuệ giác sáng nơi lòng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HUY<br/>Huy hoàng trang kinh mở<br/>Ánh sáng thắp lên rồi <br/>Đâu phải vầng dương tỏa<br/>Quang minh ở lòng tôi <br/>HUYỀN<br/>Huyền diệu lời kinh sáng<br/>Rót về bên cõi tâm <br/>Chuông xa tiếng đục trầm<br/>Gọi nắng bình minh rạng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("HỶ<br/>Nói những lời thương mến<br/>Vơi tan bao nỗi buồn<br/>Nụ cười mang trao tặng<br/>Hạnh phúc sẽ ngàn muôn",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("KHIẾT<br/>Thanh khiết giữa bụi hồng<br/>Đóa sen mùa hạ trắng<br/>Cuộc đời hoa tịnh lặng<br/>Hương gửi về mênh mông",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("KIỆM<br/>Tiết kiệm phúc cùng đức<br/>Giữ gìn cho mai này<br/>Tâm cạn rồi nhân ngã<br/>Tịnh độ chính là đây",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("KIÊN<br/>Kiên định gìn chính hạnh<br/>Giữa đen trắng cuộc đời<br/>Tùy duyên như dòng nước<br/>Mát dịu về muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LẠC<br/>Chăm sóc từng đóa hoa<br/>Hoa cùng ta mỉm cười<br/>Bước chân trong chính niệm<br/>An lạc là thảnh thơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("KÍNH<br/>Đôi bàn tay nhỏ bé<br/>Sen búp sắc hồng tươi<br/>Hàm tiếu một nụ cười<br/>Kính dâng đấng Thiện Tuệ",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LỄ<br/>Cúi đầu lễ đức Bụt<br/>Là cúi lậy tâm mình<br/>Hằng thuận với chúng sinh<br/>Tức cúng dường Đại Giác",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LIÊM<br/>Liêm khiết một tấm lòng<br/>Vẹn tròn như thái không<br/>Bao dung với tất cả<br/>Đạo đời đều dung thông",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LỘC<br/>Tặng người một chút hương<br/>Nở sớm cành mai nhỏ<br/>Lộc xuân về trước ngõ<br/>Nắng ấm muôn nẻo đường",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LỢI<br/>Làm lợi ích cho đời<br/>Cõi lòng nghe thảnh thơi<br/>Sống không vì tự ngã<br/>Sẽ thắm tươi nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("LỰC<br/>Bi trí và dũng lực<br/>Trang nghiêm tại cõi lòng <br/>Phải đâu vì danh lợi<br/>Là để gạn đục trong",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("MÃN<br/>Thanh lọc nơi tâm linh<br/>Cái nhìn được bao dung<br/>Buông rồi lòng vị kỷ<br/>Viên mãn tình mênh mông",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("MINH<br/>Đạo kỳ bay trong gió<br/>Năm sắc màu quang minh<br/>Tuệ giác tâm khai mở<br/>Ánh trăng vàng lung linh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NGHĨA<br/>Duyên trần ta gặp gỡ<br/>Trên nẻo đường phong sương<br/>Bao nghĩa tình lưu lại<br/>Giọt phù sa cố hương",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NGỘ <br/>Thị phi vốn lẽ đời<br/>Giữ tâm không phi thị<br/>Sống không lòng vị kỷ<br/>Cõi thế dạo mà chơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NGỌC <br/>Mẹ cho viên ngọc sáng<br/>Đôi mắt con rạng ngời<br/>Hạnh phúc là đơn giản<br/>Khi tâm hồn thảnh thơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NHÃ<br/>Sống cuộc đời nhàn nhã<br/>Giữa núi thẳm non xanh <br/>Ai nhọc nhằn thế sự <br/>Ta một cõi yên bình",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NHÂN<br/>Lòng nhân gốc muôn hạnh<br/>Nền tảng của con người<br/>Phật đạo từ đây mở<br/>Bồ đề là thảnh thơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NHẪN<br/>Nhẫn rồi lòng tự tại<br/>Mây trụ giữa tầng không<br/>Trong dục nước ngàn sông<br/>Đền trôi về đại hải",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("NIỆM<br/>Đôi bàn tay con chắp<br/>Từng đóa sen rạng ngời<br/>Chính niệm tròn tâm thể<br/>Nụ cười tỏa muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("PHÁT<br/>Phát khỏi lòng chính tín<br/>Bước vào nơi cửa sương<br/>Yên bình là giải thoát<br/>Mặc thế sự vô thường",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("QUANG<br/>Bình minh về trước ngõ<br/>Từng giọt sáng quang minh <br/>Nở sớm cành mai nhỏ<br/>Hương xuân gửi an bình",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("QUÝ<br/>Quen nhau một câu chào<br/>Quý nhân tình thanh cao<br/>Cạn chén trà tao ngộ<br/>Dù duyên trần hư hao",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TÀI<br/>Tài năng và ý chí<br/>Trọn vẹn hai thứ này<br/>Sự nghiệp dù gian khó<br/>Vẫn an bằng nơi đây",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TÂM <br/>Tình đời vốn sắc – không<br/>Không – sắc trái tim hồng<br/>Nằm bên lồng ngực nhỏ<br/>Dẫu vậy mà mênh mông",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TÂN<br/>Bên hiên cành hoa tươi<br/>Nở trước bình minh nắng <br/>Ý niệm vữa tĩnh lặng<br/>Thanh tân một nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THÀNH <br/>Xử thế quý chân thành<br/>Của tiền vật ngoại thân<br/>Nhọc nhằn chi phi thị<br/>Để cõi lòng bâng khuâng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THANH TỊNH<br/>Chấp đôi tay bé nhỏ<br/>Thanh tịnh niệm tròn đầy <br/>Lặng lẽ trầm hương tỏa<br/>Xuân hồng thắm hiên mây",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THẢO<br/>Hiếu thảo với mẹ cha<br/>Là kính thờ đức Phật<br/>Đừng vì đời tất bật <br/>Bỏ quên bụt trong nhà",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THẬT<br/>Thành thật với chính mình<br/>Đấy là đang hiếu thuận<br/>Đừng vì chút lợi nhuận<br/>Đánh mất sự chân thành",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THIỆN<br/>Gieo những hạt giống thiện <br/>Sẽ gặt hái điều lành<br/>Điều ác không tạo tác<br/>Quả xấu nào phát sinh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THỊNH<br/>Thịnh suy hạt sương sớm<br/>Được mất áng mây bay<br/>Thành bại cơn gió thoảng<br/>Khen chê giấc mộng dài",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THỌ<br/>Rửa sạch đôi bàn tay<br/>Nâng niu từng hạt nắng<br/>Rửa lòng cho tĩnh lặng<br/>Thọ nhuận lời Như Lai",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THÔNG<br/>Thông đạt lễ duyên sinh<br/>Cuộc đời hóa vô ngại<br/>Chớ nên vì thành bại<br/>Bỏ mất sự an bình",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THUẬN <br/>Sống thuận lẽ tự nhiên<br/>Có chi phải ưu phiền<br/>Hạ nồng ta đổi áo<br/>Đông khoác tấm bông mềm",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("THỦY CHUNG<br/>Đường đời bao ngã vấp<br/>Tương phùng một thoáng thôi <br/>Giữ gìn màu ký ức<br/>Thủy chung một nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TÍN<br/>Bỏ đi tâm tự ngã<br/>Nhịp thở nghe yên bình<br/>Chỉ cất giữ nơi mình<br/>Niềm tin về tất cả",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TĨNH<br/>Tĩnh lặng với màn đêm<br/>Nghe sương về theo gió<br/>Tĩnh lặng với hơi thở<br/>Nghe tim hồng dịu êm",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TỊNH<br/>Nhặt ngàn hạt cát nhỏ<br/>Xây dựng nên điện đài<br/>Nhặt vạn ý niệm sạch<br/>Xây tịnh độ ngày mai",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TRÍ<br/>Người trí luôn thận trọng<br/>Với bao điều đang làm<br/>Đâu cần khi quả đến<br/>Mới thấy khổ nơi tâm",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TRỌNG<br/>Tôn trọng với mọi người<br/>Là hiếu thuận chư Phật<br/>Cung kính với cuộc đời<br/>Là lễ kính chư Bụt",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TRỰC<br/>Nuôi từng ý niệm lành<br/>Lời nói luôn chính trực<br/>Hành động trong tỉnh thức<br/>Cõi lòng sẽ tịnh thanh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TRƯỜNG THỌ<br/>Hữu đức tất an khang<br/>Hữu phúc ắt trường thọ<br/>Cả hai đồng thời có<br/>Khi phúc đức gieo trồng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TỰ TẠI<br/>Trăm sông về đại hải<br/>Trôi mãi trôi thành dòng<br/>Buông nhục vinh khỏi lòng<br/>Đường đời nghe tự tại",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TUỆ<br/>Trang kinh vừa khai mở<br/>Tuệ giác thắp lên rồi<br/>Trái tim vừa mới mở<br/>Thấu hiểu bao cuộc đời",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("TƯỜNG<br/>Mỗi khi cành mai nở<br/>Ta đón tết cát tường<br/>Di lặc mùa xuân mới<br/>Nắng hồng rải muôn phương",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("VIÊN<br/>Vầng trăng nay viên mãn<br/>Thắp sáng vùng trời quê<br/>Bống tối giờ tan biến<br/>Nhịp đò bến sông khua",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("VINH<br/>Vinh nhục và thành bại<br/>Gương nước ánh trăng lay<br/>Hiểu sự đời dâu bể<br/>Nhịp nhàng cánh bướm bay",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("VÔ SỰ<br/>Hôm nay lòng vô sự<br/>Sân trước một vầng trăng<br/>Sợi khói trầm theo gió<br/>Nghe ngào ngạt hương tâm",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("XẢ<br/>Thị phi hạt bụi trần<br/>Năm tháng dài bâng khuâng<br/>Buông xả hồn thanh thản<br/>Lời kinh lòng vang ngân",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("AN BÌNH<br/>Hoàng hôn màu tím ngắt<br/>Tiếng sáo đưa lối về<br/>Trong gió làn khói bạc<br/>An bình mái tranh quê",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("AN NHIÊN<br/>Chiếc lá cuối chiều rơi<br/>Bụi trần nghe xao động <br/>Mặc đời bao con sóng<br/>Vẫn an nhiên nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("BẢO<br/>Của báu trên cõi đời<br/>Tấm lòng trải muôn nơi<br/>Trao nhau niềm tin sống<br/>Trao nhau những nụ cười",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("AN<br/> Bắt gặp chút bình an <br/>Dưới đài sen thơm ngát<br/>Hương trầm đêm ngào ngạt<br/>Thanh thản lòng… xuân sang",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("BÌNH ĐẲNG<br/>Không thị phi đen trắng<br/>Không cao thấp sang hèn<br/>Ta người đều bình đẳng<br/>Phật vị - một tòa sen",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CÁT<br/>Chuông vọng lay sương sớm<br/>Từng cánh mai chuyển mình<br/>Cát tường mùa lễ hội<br/>Nắng trái vàng trang kinh",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CHÂU<br/>Tâm hồn viên châu sáng<br/>Thanh lọc từng phút giây<br/>Ưu phiền không phát khởi <br/>Tịnh độ tại nơi này",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CHÍ<br/>Chí thành đôi tay chắp<br/>Là đóa sen rạng ngời<br/>Dâng cứng mười phương Phật<br/>Hương lòng tỏa muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("CHÍNH<br/>Buông bỏ lòng nhân ngã <br/>Chẳng hơn thua với đời<br/>Nghĩ suy luôn chính trực<br/>Đôi gót hồng rong chơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐẠT <br/>Thông đạt đời huyễn<br/>An nhiên với duyên trần<br/>Thu đông choàng thêm áo <br/>Xuân hạ chơi cùng trăng",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("DIỆU<br/>Sương hạt về kết tụ<br/>Thiền viên hoa ngát hương<br/>Diệu huyền lời kinh sớm<br/>Nuôi lớn tình yêu thương",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐỊNH<br/>Pha chén trà buổi sáng<br/>Mười phương thế giới thơm<br/>Định tuệ tâm viên mãn<br/>Tình đời hoa kết đơm",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("ĐỨC<br/>Dùng tấm lòng thánh thiện <br/>Hành xử với mọi người<br/>Thành tựu vị tha hạnh <br/>Đức ngạt ngào muôn nơi",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("DUYÊN<br/>Bàn tay ta vun đắp<br/>Thành bại thuộc vào duyên<br/>Vinh nhục ai không gặp<br/>Có chi phải ưu phiền",null);
		danhNgonList.add(dn);
		dn = new DanhNgon("GIÁC<br/>Triêu mộ lời chuông điểm <br/>Vơi tan bao niệm trần<br/>Hành hương về ánh sáng<br/>Thấy đất trời thanh tân",null);
		danhNgonList.add(dn);
	}
	
	static DanNgonUnit danNgonUnit = null; 
	
	private DanNgonUnit() {
		// TODO Auto-generated constructor stub
		
	}
	
	public static DanhNgon getDanhNgon() {
		Random rand = new Random();
		int  n = rand.nextInt(danhNgonList.size()) + 1;
		return danhNgonList.get(n-1);
	}
	
	public static void main(String[] args) {
		DanhNgon danhNgon = DanNgonUnit.getDanhNgon();
		System.out.println(danhNgon.danhNgon);
	}

}
